name: Release new version

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run make-release.sh to modify version numbers across the repo
        run: |
          LANG=C sed -i -E "s/\/reVISit-studies\/study\/v.*\/src/\/reVISit-studies\/study\/123\/src/g" src/**/*.* public/**/*.*
          LANG=C sed -i -E "s/\/revisit-studies\/study\/blob\/v.*/\/revisit-studies\/study\/blob\/${{ github.event.pull_request.title }}/g" src/**/*.* public/**/*.*
          LANG=C sed -i -E "s/\/revisit-studies\/study\/blob\/v.*/\/revisit-studies\/study\/tree\/${{ github.event.pull_request.title }}/g" src/**/*.* public/**/*.*

      - name: Commit changes
        run: |
          git config --local user.email "jackwilburn@tutanota.com"
          git config --local user.name "Jack Wilburn"
          git add .
          git commit -m "Release version ${{ github.event.pull_request.title }}"
          git tag -a ${{ github.event.pull_request.title }} -m "Release version ${{ github.event.pull_request.title }}"
          git push --follow-tags
